// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // This Prisma version's config type doesn't support `directUrl` yet, so
  // `db push`/`migrate` run against the pooled URL by default — that hangs
  // against Supabase's transaction pooler (port 6543). Run migration
  // commands with DATABASE_URL temporarily overridden to DIRECT_URL
  // (port 5432), e.g.:
  //   DATABASE_URL="$DIRECT_URL" npx prisma db push
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
